### ISSUE TITLE
Cannot access 'MainApp' before initialization

### ISSUE THREAD

**Issue by ericferreira1992** [darcy-rayner/toy-ioc#5]
I put @Injectable in all the classes I needed. But I have a class "MainApp" where I instantiate "Container" and add all providers, including this same class, see how it looks:

**app.ts**
```javascript
import { Container } from "./container";
import { Render } from "./render";

export class MainApp {
    public static instance: MainApp;

    public container: Container;
    public render: Render;

    constructor() {
        this.prepareContainerAndRegister();
    }

    public static config(){
        this.instance = new MainApp();
        return this.instance;
    }

    public start() {
        this.render = this.containerInjector.inject(Render);
    }

    private prepareContainerAndRegister() {
        this.container.addProvider({ provide: MainApp, useValue: MainApp.instance });
        this.container.addProvider({ provide: Render, useClass: Render });
    }
}
```

**render.ts**
```javascript
import { Injectable } from "./injectable";
import { MainApp } from "./app";

@Injectable()
export class Render {

    constructor(public app: MainApp) {
    }

}
```

**index.ts**
```javascript
import { Injectable } from "injectable";
import { MainApp } from 'app';

MainApp
    .config()
    .start();
```

This error is given when I try to run the application:
```
Uncaught ReferenceError: Cannot access 'MainApp' before initialization
    at Module.MainApp (app.ts:2)
    at Module.../src/render.ts (render.ts:7)
```

I tried to put @Injectable in the "MainApp" class, but still the same error.

Although this error makes sense, I need it to work the way the code looks like: MainApp creates the Container, registers the classes (and itself as singleton), and then instantiates the Render which also has MainApp as its dependency.

What should I do? :|

**Comment by darcy-rayner** [comment]
Hey @ericferreira1992 , this isn't really a supported library, I wrote it for demonstration purposes for a blog post. Maybe try Inversify JS or something similar.

**Comment by ericferreira1992** [comment]
Hey @darcy-rayner !
I solved the problem, I not add MainApp.instance in providers list of container, and when want get it I call MainApp.instance. All others providers did works fine!

I`m using toy-ioc code in my personal project, has some problem? 🤭

Thanks! The source code is amazing!
